---
# tasks file for vgmove
#
- name: vgexport
  command: umount "{{ filesystem_name }}"
  command: vgchange -an "{{ vg_name }}"
  tags: export


-name: vgimport
  command:
  command:
  tags: import

