---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Samba-related packages are installed (RedHat).
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - samba
    - samba-client
    - samba-common
    - cifs-utils
  when: ansible_os_family == 'RedHat'

- name: Ensure Samba-related packages are installed (Debian).
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - samba
    - samba-common
    - python-glade2
    - system-config-samba
  when: ansible_os_family == 'Debian'

- name: Ensure Samba is running and set to start on boot.
  service: "name={{ samba_daemon }} state=started enabled=yes"
