---
  - name: Upgrade Atomic host
    command: atomic host upgrade
    become: yes
    become_method: sudo
  
  - name: Reboot Atomic host
    command: sleep 2 && systemctl reboot
    become: yes
    become_method: sudo
    async: 1
    poll: 0
    ignore_errors: true
 