---
# do apt upgrade on {{ host }}
# example: ansible-playbook update.yml --extra-vars "host=testserver" --tags update
#
- name: update on host
  hosts: "{{ host }}"
  become: true
  roles:
    - common         
