---
# do apt upgrade on {{ host }}
# example: ansible-playbook --extra-vars "host=testserver atomic=yes|no" update.yml
# 
- name: update on {{ host }}
  hosts: "{{ host }}"
  become: yes
  roles:
    - robertdebock.update

- name: update for atomic hosts
  hosts: atomichosts
  become: yes
  roles: 
    - uschy.atomic.update
